name: test and build macosx
on:
  push:
    branches: [ build ]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
jobs:
  build_macosx:
    runs-on: ${{ matrix.os }}
    env:
      os-name: ${{ matrix.os }}
      KIVY_GL_BACKEND: 'angle_sdl2'
    strategy:
      matrix:
        os: [macos-10.15, macos-11]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt -r requirements-dev.txt
      - run: brew install create-dmg
      - run: python ./build.py test.test
      - run: python ./build.py armor.build-osx --do-upload
